# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/spartan_messanger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/spartan_messanger.proto',
  package='grpc',
  syntax='proto3',
  serialized_pb=_b('\n\x1dproto/spartan_messanger.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"<\n\x05Users\x12\x0f\n\x07msgFrom\x18\x01 \x01(\t\x12\r\n\x05msgTo\x18\x02 \x01(\t\x12\x13\n\x0bisBroadcast\x18\x03 \x01(\x08\"\x16\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\"M\n\x07Message\x12\x10\n\x08\x66romUser\x18\x01 \x01(\t\x12\x0e\n\x06toUser\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\x13\n\x0bisBroadcast\x18\x04 \x01(\x08\x32\x91\x01\n\x10SpartanMessanger\x12.\n\nReceiveMsg\x12\r.grpc.Message\x1a\r.grpc.Message\"\x00\x30\x01\x12%\n\x07SendMsg\x12\r.grpc.Message\x1a\x0b.grpc.Empty\x12&\n\x07\x43onnect\x12\x0b.grpc.Users\x1a\x0c.grpc.Status\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='grpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=46,
)


_USERS = _descriptor.Descriptor(
  name='Users',
  full_name='grpc.Users',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgFrom', full_name='grpc.Users.msgFrom', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgTo', full_name='grpc.Users.msgTo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isBroadcast', full_name='grpc.Users.isBroadcast', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=108,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='grpc.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='grpc.Status.code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=132,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='grpc.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromUser', full_name='grpc.Message.fromUser', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toUser', full_name='grpc.Message.toUser', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='grpc.Message.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isBroadcast', full_name='grpc.Message.isBroadcast', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Users'] = _USERS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'proto.spartan_messanger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Users = _reflection.GeneratedProtocolMessageType('Users', (_message.Message,), dict(
  DESCRIPTOR = _USERS,
  __module__ = 'proto.spartan_messanger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Users)
  ))
_sym_db.RegisterMessage(Users)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'proto.spartan_messanger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Status)
  ))
_sym_db.RegisterMessage(Status)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'proto.spartan_messanger_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Message)
  ))
_sym_db.RegisterMessage(Message)



_SPARTANMESSANGER = _descriptor.ServiceDescriptor(
  name='SpartanMessanger',
  full_name='grpc.SpartanMessanger',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=214,
  serialized_end=359,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveMsg',
    full_name='grpc.SpartanMessanger.ReceiveMsg',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMsg',
    full_name='grpc.SpartanMessanger.SendMsg',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='grpc.SpartanMessanger.Connect',
    index=2,
    containing_service=None,
    input_type=_USERS,
    output_type=_STATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPARTANMESSANGER)

DESCRIPTOR.services_by_name['SpartanMessanger'] = _SPARTANMESSANGER

# @@protoc_insertion_point(module_scope)
